### ISSUE TITLE
ManifestStaticFilesStorage vs CachedStaticFilesStorage

### ISSUE THREAD

**Issue by saulshanabrook** [evansd/whitenoise#10]
Why do you use ManifestStaticFilesStorage instead of CachedStaticFilesStorage?

It seems like the Cached one would be better on a system like heroku, because the Django docs say that

> This is mostly useful for situations in which you don’t have access to the file system.

What are the advantages of the Manifest?

**Comment by hheimbuerger** [comment]
Not entirely sure on the consequences of this. Are you saying that ManifestStaticFilesStorage *does work* on Heroku (because being able to have access to the filesystem during the `collectstatic` phase is enough) or that it *does not* (because it would need to make changes to the filesystem in the run phase)?

**Comment by evansd** [comment]
It _does_ work on Heroku. It only needs to be able to write to the filesystem during the build phase, but it can still read from it during the run phase.
