### ISSUE TITLE
use of 'whitenoise.runserver_nostatic' (switches self off in production?)

### ISSUE THREAD

**Issue by andytwoods** [evansd/whitenoise#104]
Sorry for the silly Q. I am still learning.

You advice using 'whitenoise.runserver_nostatic' on development servers. Can I leave in this app when on Production? That is, will it detect eg debug=True and switch itself off?

Its the requirement for the above app to be above 'django.contrib.staticfiles' which makes it a little fiddly to have different Production and Base settings files, you see.

Many thanks,
Andy.

**Comment by evansd** [comment]
Short answer: yes, it will do the right thing in production and so there's no need to have different production and development settings.

The slightly more complicated answer is that it won't switch itself off as such, because what it's doing is forcing `runserver` into production mode (with regard to static files) all the time. `contrib.staticfiles` comes with its own wrapper around `runserver` which takes over static file handling when in `DEBUG` mode. All `whitenoise.runserver_nostatic` does is disable this behaviour and use the standard, production-mode `runserver` regardless of whether `DEBUG` is enabled or not.

Hope that makes some kind of sense!

**Comment by andytwoods** [comment]
thanks! :D

Really appreciate the work you've guys done on this app. Making our lives a lot easier :)
