### ISSUE TITLE
django debug toolbar

### ISSUE THREAD

**Issue by oppianmatt** [evansd/whitenoise#109]
Using whitenoise and django-debug-toolbar together makes it really slow. It looks like that django debug toolbar is running all it's panels/collectors for the static media requests.

Is there a way to shortcircuit this, perhaps ordering of the middleware? Or some setting to disable debug toolbar on requests handled by whitenoise?

**Comment by evansd** [comment]
I'd suggest:
 1. make sure the WhiteNoise middleware comes above the debug toolbar middleware;
 2. make sure you're using the new `MIDDLEWARE` setting rather than the old-style `MIDDLEWARE_CLASSES` settings.

If that doesn't work it might be possible to do something with the [SHOW_TOOLBAR_CALLBACK](https://django-debug-toolbar.readthedocs.io/en/stable/configuration.html#toolbar-options) setting to disable it for static requests. But you'd be better of asking the Django Debug Toolbar project about that as I'm not really an expert on it.

**Comment by oppianmatt** [comment]
debug toolbar recommends to go first in the middleware, which is what I had. But trying it out where I splice it in after whitenoise (making sure whitenoise middleware is first) and it manages to avoid profiling the static content calls.

```
if DJANGO_TOOLBAR:
    # splice debug middleware after whitenoise
    MIDDLEWARE_CLASSES[:1] = [
        'debug_panel.middleware.DebugPanelMiddleware',
    ]
```
