### ISSUE TITLE
Better production/dev parity

### ISSUE THREAD

**Issue by blopker** [evansd/whitenoise#113]
Hey, first off, thank you for this lib. I use it for all the apps, so great.

I just wanted to raise an issue we've ran in to regarding the differences between dev and prod.

The issue arises when `DEBUG` is on. Missing images do not throw errors like they do in production. Say there's an included template like:
```html
{% load staticfiles %}
<img src="{% static 'img/home/mobile.png' %}" srcset="{% static 'img/home/mobile_2x.png' %} 2x"/>
```
And pretend the `mobile.png` is missing (or has the wrong extension in our case). When `DEBUG` is on the page will load fine and if the browser decides to use the 2x image, no 404 will be shown for the 1x image.

However, in production Django will try and include the template above and fail at finding the hashed version of the image. This will throw an exception and remove the whole template from the page, but render the rest of the page fine. 

The production behavior is good, I think. What I'm interested in discussing is if we can get that same behavior with `DEBUG` on? e.g. throw an exception with the image name in the console. This would make naming issues much more visible in development.

If this is something you'd be interested in I could put together a PR.

Cheers!

**Comment by evansd** [comment]
Hi @blopker, glad you've found WhiteNoise useful.

I agree with you that it would better to throw an error (or at least log a warning) for missing assets in development. However the current behaviour is part of Django itself and not WhiteNoise, so it's an issue that needs to be raised with the Django project.

At the moment, any storage backend which subclasses [HashedFilesMixin](https://github.com/django/django/blob/cc0bb07013ed3e7ec58ee6da014ed3094a1a350f/django/contrib/staticfiles/storage.py#L121) (as WhiteNoise does) will exhibit the same problem because that `url` method behaves differently depending on the value of `DEBUG`.

I'll close this issue as it's not specifically an issue for WhiteNoise, but if you get anywhere in solving this problem for Django more widely then feel free to post any updates here.

**Comment by blopker** [comment]
Fair enough! Thanks for your quick response. 

I wonder if there's a way to test for missing images.

Cheers!

**Comment by evansd** [comment]
I forgot to mention this before, but with WhiteNoise you can always test your app by running it locally with `DEBUG = False` (after having run `collectstatic`). WhiteNoise will serve your static files exactly as it would in production so you should be able to spot any problems here.
