### ISSUE TITLE
login required condition to serve files

### ISSUE THREAD

**Issue by jxrossel** [evansd/whitenoise#124]
Hi,

Not really an issue, but rather a question. Is there a way to limit static files access (or access to a subset of them) to authenticated users ?

Cheers,

Jonathan

**Comment by evansd** [comment]
No, this isn't something WhiteNoise supports as it assumes that all static files are publicly cachable and sends headers accordingly.

**Comment by edmorley** [comment]
In addition, to check whether a user is authenticated, (for Django at least) the WhiteNoise middleware would need to be placed after the Django session/authentication middleware, which makes database requests etc. This would negate the performance benefits of WhiteNoise.

**Comment by jxrossel** [comment]
Ok, thanks for your answer ! I was about to suggest it as a future development but Edmorley just pulled the rug out from under me

**Comment by Schnouki** [comment]
Hi,

First, sorry to reply to a closed issue, but I think it makes more sense that opening a new one on this topic.

I'm also interested in restricting access to some static files. Namely sourcemaps for JS (and CSS) files. Since it wouldn't be efficient to use Django session/authentication for this, I implemented it in a custom middleware using another method: the middleware sets a (session, signed) cookie on the static sub-domain when there's a request from an authorized user (staff users in my code), and checks for this cookie to allow access to `.map` static files.

Here is the code: https://gist.github.com/Schnouki/32603c54bcd126fa86ea1fa15ac1b82a

Hope this helps. And if it does and some people actually find this a good idea, I'd be interested in writing a PR to merge this in WhiteNoise 😉

**Comment by evansd** [comment]
Hi @Schnouki,

This looks interesting, but you need to be careful with caching when using this. You'll need to replace the caching headers on authenticated responses, otherwise private files will end up in the cache.
