### ISSUE TITLE
Throw Errors in Django in Debug when it will be thrown in Production

### ISSUE THREAD

**Issue by joesolly** [evansd/whitenoise#127]
We have run into a problem a few times where a developer will put in a templatetag to an invalid file: `{% static 'js/apps.jss' %}` and the development environment quietly hides the issue. When we get to a production environment, the file is not found in the static files manifest and the manifest attempts to create a hashed version of it and throws an exception when the file is not found. We were thinking it might make sense to add a check in the CompressedManifestStaticFilesStorage url function to check to see if a file exists and throw an error there if it doesn't. That way, we can get the same errors in development as we see in production.

Would anyone else have any thoughts on if this should go here or what they think about the feature?

**Comment by evansd** [comment]
Hi @joesolly,

Yes I would definitely prefer these errors to get thrown in development as well as in production, but the current behaviour is defined by Django itself, rather than by WhiteNoise. `CompressedManifestStaticFilesStorage` is just a thin wrapper around Django's `ManifestStaticFilesStorage` which creates compressed files during the `collectstatic` run, but otherwise doesn't do anything else. So this is an issue that needs to be raised with Django itself.

Thanks,

Dave

**Comment by joesolly** [comment]
Hi @evansd ,

While I agree it would be great to get it into core Django, I imagine it might take awhile to get merged and deployed to a production version. So in the mean time, this is what I did to work around the problem. I'll leave it here in case anyone with the same issue stumbles across this thread.

```
from django.contrib.staticfiles import finders
from django.conf import settings

from whitenoise.django import GzipManifestStaticFilesStorage

class DebugErroringGzipManifestStaticFilesStorage(GzipManifestStaticFilesStorage):

    def url(self, name, force=False):
        if settings.DEBUG:
            if finders.find(name) is None:
                raise ValueError("The file '%s' could not be found with %r." % (name, self))
        return super(DebugErroringGzipManifestStaticFilesStorage, self).url(name)
```

Thanks,
Joseph
