### ISSUE TITLE
ETag and If-None-Match

### ISSUE THREAD

**Issue by guyhughes** [evansd/whitenoise#129]
Would you be willing to accept a contrib package that implements ETag and If-None-Match conforming to [RFC 7232 s. 2.3](https://tools.ietf.org/html/rfc7232#section-2.3) with a full test suite?

I have one.

**Comment by evansd** [comment]
Hi @guyhughes, I'd be interested in taking a look. I've considered adding this before but held off for two reasons:
 * Due to WhiteNoise's architecture it would involve hashing all the static files on application boot which might add considerably to the boot time.
 * I want to push people in the direction of using an immutable file versioning system like `ManifestCacheStorage`, in which case the ETag stuff becomes irrelevant anyway.

That said, if you've got the code written already I'd be interested to see whether it could be merged in as it would be a nice extra feature to have.

**Comment by guyhughes** [comment]
🥇 

> I want to push people in the direction of using an immutable file versioning system like ManifestCacheStorage
My use case was built around a pre-existing static asset build system that adds file hashes.  

ETag is nice when the non-immutable file versions rollback.

**Comment by evansd** [comment]
ETag support has been added in the upcoming 4.0 release. I've realised it's not necessary to hash the files in order to generate ETags which are more useful than the Last Modified header; we can just do what nginx does and use the file mtime and size and we still get an identifier that's robust against rollbacks.
