### ISSUE TITLE
Question: Is useless compressing during the build if I'm using the whitenoise's storage class?

### ISSUE THREAD

**Issue by semente** [evansd/whitenoise#136]
Hello,

I'm compressing the static files using the following command during the build process of my application:

```
python -m whitenoise.compress /app/_assets/static
```

I have plans to cache the static files forever using your `whitenoise.storage.CompressedManifestStaticFilesStorage`.

Will both work well together? If so, will I get benefits by compressing the files during the build (i.e. do it will compress only once)?

Thanks!

**Comment by evansd** [comment]
If you're using ``CompressedManifestStaticFilesStorage`` then you shouldn't also compress your files beforehand. The reason is that the caching process will need to rewrite some of your files so that they reference the new names of your assets and this will need to be done before they are compressed.
