### ISSUE TITLE
Make whitenoise faster

### ISSUE THREAD

**Issue by ionelmc** [evansd/whitenoise#141]
I would like to hear your thoughts on this topic before doing anything. Do you think it be possible to get responses under 50ms with whitenoise on cpython?

Most obvious thing that can be improved would be removing/avoiding unnecessary function calls, but then comes the question of what is part of the public api, and what doesn't need to be extensible. Do you have any guidelines regarding this?

**Comment by evansd** [comment]
Thanks for getting in touch. I would definitely be open to patches which made a measurable improvement to performance. So far I haven't put effort into micro-optimising the code for two reasons:
1. In performance sensitive contexts most people run whitenoise behind a cache so improvements to whitenoise only affect the cache-miss response time, which usually isn't a priority.
2. Whitenoise is designed to do as much work as possible on initialisation, so there's actually not much code on the hot path. The response time is most likely to be dominated by time spent in the server (gunicon, waitress etc.) and in Django itself (if you're using it) rather than in Whitenoise.

Once we have the `StaticFile` instance (which in production mode is just a lookup in the `files` dict) all the work is done in the [serve](https://github.com/evansd/whitenoise/blob/1266e8c44264f34a6920fc75085f3207e0ab14b6/whitenoise/base.py#L75) method, and most of the time there is in calling [get_response](https://github.com/evansd/whitenoise/blob/1266e8c44264f34a6920fc75085f3207e0ab14b6/whitenoise/responders.py#L41) on the `StaticFile`.

The Range header handling complicates things a bit but that's a rare case and most requests can be served pretty simply.

In terms of the API, none of this is officially documented but I'd say that the `get_response` method signature is semi-public in that some people have produced alternative integrations that use it so that interface should be preserved. Anything else can be changed if necessary.

Thanks!
