### ISSUE TITLE
MIDDLEWARE order

### ISSUE THREAD

**Issue by philgyford** [evansd/whitenoise#145]
The docs say that `WhiteNoiseMiddleware` should come after Django's `SecurityMiddleware`, but don't refer to any or Django's other middlewares. So *maybe* it doesn't matter, but some other middlewares have specific instructions and I'm not sure if they're relevant.

For example `django.middleware.cache.UpdateCacheMiddleware` "must be before those that modify the `Vary` header" - does Whitenoise do that?

And `django.middleware.gzip.GZipMiddleware` must go "before any middleware that may change or use the response body". Again, is that Whitenoise?

Apologies for my ignorance, but without delving into the gritty details of how these things work I'm not sure if I'm setting things up correctly.

**Comment by evansd** [comment]
Yes, I can see how this is a bit confusing. The basic rule is that WhiteNoise should come before all other middleware, with `SecurityMiddleware` as the only exception. In fact nothing will break if you put it before `SecurityMiddleware` as well, but there are a few security features it makes some sense to apply to static files as well which is why I make that recommendation.

I'll try to update the docs to make this clearer.

**Comment by edmorley** [comment]
(Dave's response raced with mine, but might as well post anyway :-))

That's a good question :-)

The rough idea is that WhiteNoise comes as soon as possible, since every extra middleware means slower serving of static assets. The reason for saying `SecurityMiddleware` should come first, is that it performs HTTP->HTTPS redirecting as well as setting of security related header ([see here](https://github.com/django/django/blob/1.11.5/django/middleware/security.py)), which ideally should happen even when using WhiteNoise.

Virtually every other middleware should go after, since WhiteNoise already handles caching/headers/gzip itself, so doesn't need any of the other middleware to be run (and doing so will only slow down the response).

**Comment by philgyford** [comment]
Ah, thanks! Django's middleware ordering is like some kind of logic puzzle at the best of times, and this was raising the difficulty level :)

I've promoted `WhiteNoiseMiddleware` above both `UpdateCacheMiddleware` and `GZipMiddleware` now!

**Comment by edevil** [comment]
I submitted #171 which adds more documentation about the order of middlewares since I encountered a problem because of it.

**Comment by edmorley** [comment]
@evansd, hi! Thank you for taking care of the docs update :-) I really need to get back up to speed with Whitenoise again and finish up the few WIPs I have locally (I've taken a detour to the JS dark side recently 😆).
