### ISSUE TITLE
Enable WHITENOISE_KEEP_ONLY_HASHED_FILES by default

### ISSUE THREAD

**Issue by edmorley** [evansd/whitenoise#146]
WhiteNoise 4 adds a `WHITENOISE_KEEP_ONLY_HASHED_FILES` option, which causes the non-hashed files to be deleted. Given this is a major version bump release that's not yet come out of beta, I wondered whether the option should be set to `True` by default instead of the current `False` - so that WhiteNoise does the most efficient thing out of the box?

I was also thinking it would be good to upstream this behaviour - seems like there is a good chance it would be accepted:
https://code.djangoproject.com/ticket/27929

**Comment by marfire** [comment]
I don't think that the default should be to delete the non-hashed files.

Putting aside the backwards-compatibility issue, deleting the files is an inherently riskier option. If you keep the files when you don't need them you've simply wasted a bit of space. If you delete the files when you do need them, your site will break. Deleting the files is a performance optimization that you should do when you're sure that 100% of your static file references will be dynamically generated by Django. The *default* option should be to do the thing that just works, regardless.

**Comment by evansd** [comment]
Yes, I agree with keeping the default as is. I think I'll recommend enabling it in the docs though.

**Comment by evansd** [comment]
Just to add to this, I think the risk logic is reversed for new projects, which is why I'll recommend enabling it at the start for new projects. That way if you aren't generating your static file references correctly then things won't work, rather than silently working in a sub-optimal way, which is actually more risky.

**Comment by edmorley** [comment]
Makes sense - thank you :-)

**Comment by marfire** [comment]
@evansd: Your comment implies that referencing files by the original names is *incorrect* - I disagree! There are absolutely use cases for having Django as your backend (and using it to manage static files) that don't involve using it to dynamically create your front-end pages. For example, you might have a mobile app with bundled front-end code that uses the Django backend and needs to access static files by their regular names. `whitenoise` currently has good support for this scenario, since you can rely on the versioned files being cached forever while using `WHITENOISE_MAX_AGE` to control the HTTP caching for the regular flies.

I think it's fine for you to suggest turning on this option in the documentation if you think it represents a good optimization for a common use case, my point is just that this isn't a backwards-compatibility issue, or a new vs old project issue, it's a matter of choosing a default that works for all use cases.
