### ISSUE TITLE
Flask is not using WhiteNoise when wrapping app.wsgi_app

### ISSUE THREAD

**Issue by chhantyal** [evansd/whitenoise#172]
I commented here #165, but it's bit different issue.

I created flask app and wrapped like this:

`app.wsgi_app = WhiteNoise(app.wsgi_app, root='static/')`

However, Flask is not using whitenoise to serve static files. You can verify this by checking headers in served static files eg:

```
Accept-Ranges:bytes
Cache-Control:public, max-age=43200
Content-Length:22
Content-Type:text/css; charset=utf-8
Date:Fri, 02 Feb 2018 16:31:28 GMT
ETag:"1514995991.0-22-4149482383"
Expires:Sat, 03 Feb 2018 04:31:28 GMT
Last-Modified:Wed, 03 Jan 2018 16:13:11 GMT
Server:Werkzeug/0.14.1 Python/3.6.4
```
I have a sample application (see `app.py`) here https://github.com/chhantyal/flask-docker

**Comment by evansd** [comment]
That looks like WhiteNoise working correctly to me. What headers were you expecting to see?

**Comment by chhantyal** [comment]
As far as I understand, default `max age`is 60 seconds? Also, if I remove whitenoise, I get same headers, which means files are served by Flask.

**Comment by evansd** [comment]
Ah, OK. I see the problem. You haven't set `prefix` so WhiteNoise is serving your static files at the URL root. If you request http://localhost:8000/style.css you'll see the file being served by WhiteNoise.

The fix is just to set `prefix` as well as `root`:
```python
app.wsgi_app = WhiteNoise(app.wsgi_app, root='static/', prefix='static/')
```

But I'd also be tempted to make `root` an absolute path, rather than relying on the app being run with a particular working directory:
```python
import os

app.wsgi_app = WhiteNoise(app.wsgi_app,
        root=os.path.join(os.path.dirname(__file__), 'static'),
        prefix='static/')
```

**Comment by chhantyal** [comment]
Thank you so much for that detailed explanation, solved my issue which was hard to debug.

Making root absolute path totally makes sense  👍
