### ISSUE TITLE
Whitenoise throws MissingFileError for files in comments

### ISSUE THREAD

**Issue by GvS666** [evansd/whitenoise#185]
I have a css file with commented code like this:
`
/* background-image: url(../addons/pager/icons/loading.gif) !important; */
`
and whitenoise throws error about missing file.

**Comment by edmorley** [comment]
Hi! This is a duplicate of #58, #167, #178, #182 and #184.

This issue is due to an upstream Django bug:
https://code.djangoproject.com/ticket/21080#comment:7

There is a workaround mentioned here that might help in the meantime:
https://github.com/evansd/whitenoise/issues/182#issuecomment-379120958

Also, if you were up for opening a PR to make this case more obvious in the docs, it would be gladly accepted :-)
http://whitenoise.evans.io/en/latest/django.html#troubleshooting-the-whitenoise-storage-backend

**Comment by GvS666** [comment]
Hi @edmorley, so sorry about that. I should go to sleep now. Thanks for the great library and quick response!

**Comment by edmorley** [comment]
No problem! And the thanks should go to @evansd :-)
Have a great weekend!
