### ISSUE TITLE
CompressedManifestStaticFilesStorage equivalent outside Django

### ISSUE THREAD

**Issue by twosigmajab** [evansd/whitenoise#228]
Currently the docs don't mention how to get equivalent functionality provided by `CompressedManifestStaticFilesStorage` outside Django.

If you might accept a PR adding something equivalent (at least for Flask?), you could also document a [PRs welcome](https://github.com/evansd/whitenoise/issues/228) link to maybe get this added sooner.

Thanks for the great work on Whitenoise!

**Comment by evansd** [comment]
`CompressedManifestStaticFilesStorage` is a plugin for Django's `contrib.staticfiles` system so it doesn't really make sense outside of Django.

If you want to create compressed files outside of Django then WhiteNoise already has a [tool for that](http://whitenoise.evans.io/en/stable/base.html#compression-support).

If you want to create files with unique names that can be cached forever (like Django's `ManifestStaticFilesStorage` does) then that's a bit more complicated as it will need to hook into the templating system of whatever framework you are using in order to make sure the right URLs get generated. I don't think it's possible to create a fully generic system for doing that.

Once you've generated the unique names, it's not too difficult to get WhiteNoise to send the right caching headers though. You just need to configure the [immutable_file_test](http://whitenoise.evans.io/en/stable/base.html#immutable_file_test) setting to mtach filenames with the right pattern.

**Comment by evansd** [comment]
@twosigmajab As a general rule it's not a good idea to make significant edits to the title or description of an issue once there are replies. It makes it hard for other people to follow the discussion, and it doesn't trigger a notification to other participants in the thread that there's anything new to respond to.

**Comment by twosigmajab** [comment]
I made the edits before there were any replies. I did that rather than creating a new ticket (with the more useful title and description) to reduce new ticket churn, which some maintainers prefer. In this case, I think GitHub should just send out an email notification when these are edited. In any case, thanks for telling me your preferences, will adhere to them going forward.

**Comment by twosigmajab** [comment]
As for the actual issue, thanks for the helpful reply! I'll look into those pointers asap and post back here once I have.

**Comment by evansd** [comment]
> I made the edits before there were any replies

Ah, I see! I would have just read the text in the email notification and so wouldn't have seen the edits.

I guess it makes sense to edit the title so it's an accurate summary of the current topic of the issue (plus github makes it obvious in the UI how and when a title's been edited so it shouldn't confuse anyone too much). I would still avoid making large scale edits to comments though. Or at least, leave the original text but with strikethough.

Thanks
