### ISSUE TITLE
Compress/Pre-compiler Documentation

### ISSUE THREAD

**Issue by northborn** [evansd/whitenoise#29]
Would love to see some documentation on how to get this to work with django compressor and SCSS or LESS precompilers.

**Comment by anentropic** [comment]
Same... I'm getting 404 from (only) the less files eg `/static/CACHE/css/responsive.9b122fb090ab.css`

the other static files all work fine via whitenoise

**Comment by anentropic** [comment]
so, the reason I get 404 is I hadn't set up any uwsgi/nginx to serve static files (if I disable whitenoise then all my static files 404) ...so far so obvious

but this indicates that whitenoise is not serving the static files generated by django-compressor

is there a workaround? is this something that it should do/makes sense to do? at the least this could be mentioned in the docs

**Comment by danreeves** [comment]
This is because whitenoise generates a list of all the files it can serve on app startup while compressor generates files on the fly. You can work around this by manually running a compress before startup.

For example, in my dokku/heroku app I have a post_compile script hook that runs `python manage.py compress --force` before whitenoise starts up.

**Comment by anentropic** [comment]
ok thanks I'll try that

**Comment by anentropic** [comment]
:+1:
