### ISSUE TITLE
Collectstatic on heroku with assets not in repo?

### ISSUE THREAD

**Issue by bwarren2** [evansd/whitenoise#34]
How can I use Whitenoise on Heroku with static assets I don't include in my git repo?

I install lots of js tools via bower, and try to keep my repo clean by excluding my bower installs (but leaving the bower.json).  This means that those static files are not in the files Heroku sees on push, so collectstatic() can't include them in the manifest.  When I was using django pipeline, I got around this by running collectstatic() with production settings from my local repo (that had the bower installs) and writing to s3.  

What is the best way to proceed?  I guess I could git submodule all of the tools I use, but this would quickly slow down my deploys and make my slug bigger than I desire.  Alternatively, I could include my build artifacts (but not the bower sources) in my repo, but that seems unclean.

**Comment by edmorley** [comment]
I guess you could either use `WHITENOISE_ROOT` (http://whitenoise.evans.io/en/latest/django.html#WHITENOISE_ROOT) or else `application.add_files()` (http://whitenoise.evans.io/en/latest/base.html#WhiteNoise.add_files)? :-)

**Comment by edmorley** [comment]
eg:
```python
application = DjangoWhiteNoise(application)
application.add_files('/absolute/path/to/some/other/files')
```

**Comment by evansd** [comment]
My recommendation would be to include everything you need to successfully build your project in the repo itself. It's true that this bulks out the repo, but the simplicity it buys you is enormous and these days storage is cheap and networks are fast.

The way I like to handle things with Heroku is first to disable the automatic collectstatic run by creating a file called: `.heroku/collectstatic_disabled`

Then I create a script in `bin/post_compile` which does everything necessary to build all my static assets (including run gulp, grunt, etc.) and then runs `collectstatic`.

This way I can run that command locally to test things and then be reasonable confident that when I push it to Heroku it will produce the same output.

Hope that's helpful.

**Comment by vyscond** [comment]
take a look at this project https://github.com/nvbn/django-bower i think you can save a bower.json on your repo and them trigger the download to your bower's pkgs with the default collectstatic command!

**Comment by hugorodgerbrown** [comment]
Not sure if this is of interest - but we had the same issue - and we had a lot of front-end build cruft that we didn't want in the repo. We ended up building a Docker 'frontend compiler' that we don't commit, and then committing the output (as per David's comment). It does result in some double-counting (duplicated static files), but it does work, and crucially (for us, as a team) it ensures that we get a consistent build every time, across all developers - we had an ongoing nightmare with Node / Bower / Grunt discrepancies.

Details here - http://tech.yunojuno.com/using-docker-to-contain-a-node-front-end-build-system

**Comment by RyanBalfanz** [comment]
@bwarren2 You don't need to include your `bower_components` assets, as @evansd correctly suggests. And Docker seems like super overkill IMO.

Here's what I do, it works really well for me. YMMV.

Use a multi-buildpack in your [app.json](https://devcenter.heroku.com/articles/app-json-schema) so that you can leverage the [https://github.com/apiaryio/heroku-buildpack-nodejs-grunt](https://github.com/apiaryio/heroku-buildpack-nodejs-grunt) buildpack to build your frontend's assets using bower/grunt.

```app.json
	"buildpacks": [{
		"url": "https://github.com/apiaryio/heroku-buildpack-nodejs-grunt"
	}, {
		"url": "https://github.com/heroku/heroku-buildpack-python"
	}]
```

In your `package.json` to tell heroku to do a `bower install`, `grunt`, or whatever you need to do by setting your pre/postinstall scripts.
```
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "preinstall": "bash ./preinstall.sh",
    "postinstall": "bash ./postinstall.sh"
  },
```

Where, `postinstall.sh` is something like this:

```
#!/bin/bash -ex

echo "Post-install started"

./node_modules/bower/bin/bower --verbose install
./node_modules/grunt-cli/bin/grunt --verbose build # e.g. concat, uglify, etc.

echo "Post-install completed"
```

Whatever artifacts you create there should sit in a directory listed in your Django app's `settings.STATICFILES_DIRS`.

Now, so long as you've configured Django's static files correctly to be served from you build artifacts (i.e. your `STATIC_ROOT` via `STATICFILES_DIRS`, you should be good to go. Heroku will run `manage.py collectstatic` for you during the heroku-buildpack-python build phase -- make sure it captures everything bower installed, or anything else you've built with grunt.

Note: You might also want to set `NPM_CONFIG_PRODUCTION= false` to install any `devDependencies` declared in your package.json rather then polluting your `dependencies` and relying on the default value.
