### ISSUE TITLE
SSL handshake and open() errors after enabling whitenoise

### ISSUE THREAD

**Issue by onyeibo** [evansd/whitenoise#452]
### Python Version

3.10.8

### Django Version

4.1.3

### Package Version

6.2.0

### Description

I enabled whitenoise on a hosted django site following the directions here: http://whitenoise.evans.io/en/stable/django.html
The site now throws Server Error (500).  Before introducing whitenoise, the site was up and running fine.

While uWSGI is still up and serving, Nginx is now complaining.  Two errors are recurring as per` /var/log/nginx/error.log`.:

```
2022/12/11 06:38:53 [error] 2667#2667: *7467 open() "/var/www/html//ab2h" failed (2: No such file or directory), client: XXX.XXX.XX.XX, server: ~^(www\.)?(site\.com)$, request: "GET /ab2h HTTP/1.1", host: "YYY.YYY.YYY.YYY"
2022/12/11 06:39:02 [crit] 2668#2668: *7477 SSL_do_handshake() failed (SSL: error:0A00006C:SSL routines::bad key share) while SSL handshaking, client: XXX.XXX.XX.XX, server: 0.0.0.0:443
2022/12/11 07:07:31 [error] 2668#2668: *7481 directory index of "/var/www/html//" is forbidden, client: XXX:XXX:X:XXX::XXX, server: ~^(www\.)?(site\.com)$, request: "GET / HTTP/1.1", host: "[YYYY:YYYY::YYYY:YYYY:YYYY:YYYY]"
```
Where did I go wrong?

**Comment by adamchainz** [comment]
This doesn't seem to be anythign to do with Whitenoise. Those log messages come from uwsgi. It could be that some change existed in your uwsgi configuration or permissinos, and only by reloading uwsgi did you encounter the errors.

Closing because there's not really anything we can do here.

Also beware that uwsgi is in maintenance mode - I'd recommend switching to gunicorn.
