### ISSUE TITLE
AWS Cloud Front supports GZIP - update docs

### ISSUE THREAD

**Issue by gciding** [evansd/whitenoise#59]
Hi David

Great project! A quick note -- it may be worth updating the FAQs because AWS Cloud Front now supports GZIP :+1: 

https://aws.amazon.com/blogs/aws/new-gzip-compression-support-for-amazon-cloudfront/

**Comment by edmorley** [comment]
I was going to update the docs for this, however from what I can tell, S3 doesn't support varying gzip, it's just CloudFront that does. django-storages only seems to support CloudFront from what I can tell? (And as such, the docs reference to S3 is still correct)
https://django-storages.readthedocs.org/en/latest/

That said, I know CloudFront uses S3 itself, so perhaps django-storages can still be used to upload to the S3 bucket from which CloudFront pulls?

**Comment by evansd** [comment]
Yes, you're right. It's now possible to get gzip compression when serving from S3 if you serve via CloudFront, but I don't think this is something django-storages can automatically configure for you.

I have plans to add [Brotli](https://en.wikipedia.org/wiki/Brotli) support to WhiteNoise so I can keep one step ahead of S3 ;)

If I was going to update the docs I'd add a note saying the it's now possible to get gzip support using CloudFront with S3, but if you've got to setup CloudFront anyway then you might as well use it with WhiteNoise rather than S3 as the setup is much simpler and the performance will be the same.
