### ISSUE TITLE
Serving Media Files

### ISSUE THREAD

**Issue by schacki** [evansd/whitenoise#62]
Hi all,

I am wondering how to handle my media files (MEDIA_URL, MEDIA_ROOT), because currently they do not seem to be served.

So first of all, is it recommended that I serve my media files via whitenoise anyway? And if so, what is the best way to do so? I was thinking about add_files().

And if things work, I'd be happy to update the docs.

Thanks for your help
Juergen

**Comment by edmorley** [comment]
WhiteNoise only scans the files at startup for security and performance reasons, so can't support user-generated files, so doesn't support serving Django media files.

https://github.com/ryanmcgrath/django-rednoise (a fork of WhiteNoise) does support doing so, by dynamically adding new files to the cached file list. However I haven't looked closely enough at the implementation to see whether it regresses any of the performance or security concerns that caused WhiteNoise to not take a similar approach.

**Comment by mrmachine** [comment]
RedNoise is only compatible with WhiteNoise `<2.0`, and it sounds like the author isn't keen on maintaining it and thought  most of its features would be or had been merged into WhiteNoise.

Serving uploaded media is very important. Without this feature, we still need nginx in front to serve media (which are then cached by CDN). Please add a setting that allows on-demand population of the cache, instead of a single scan at startup time, so we can use it to serve media directly.

**Comment by edmorley** [comment]
There is such a setting already:
http://whitenoise.evans.io/en/stable/django.html#WHITENOISE_AUTOREFRESH

However it really really isn't recommended - see the reasons here:
http://whitenoise.evans.io/en/latest/django.html#serving-media-files

**Comment by mrmachine** [comment]
Ah, that's great. Thanks! It seems it is not possible to use `add_files()` (to tell WhiteNoise where to find media) when using the `MIDDLEWARE_CLASSES` method of Django integration?

**Comment by zathazass** [comment]
Yeah it's right i tried in many way but not still working...We use another technique
