### ISSUE TITLE
Suggestions for Flask Application

### ISSUE THREAD

**Issue by cancan101** [evansd/whitenoise#66]
Currently "WhiteNoise works with any WSGI-compatible app but has some special auto-configuration features for Django". What, if at all, is the suggestion for using whitenoise with a Flask application?

Flask already has a performant [`send_file`](http://flask.pocoo.org/docs/0.10/api/#flask.send_file) that unlike Django's static serving, which works only in development, will work in production as well.

**Comment by evansd** [comment]
I don't use Flask myself so I haven't looked into it much. The main benefit of using WhiteNoise over what Flask provides by default would be the support for serving pre-compressed (gzipped) content. But as Flask is much less opinionated then Django about how static files get managed I don't think it will be possible the get the same kind of automatic integration as we can with Django.

If you, or anyone else who uses Flask heavily, want to investigate further and see if it's possible to package WhiteNoise as Flask extension I'd be very happy to accept contributions.

**Comment by cuducos** [comment]
Within Flask the way to do it is to wrap [`Flask()`](http://flask.pocoo.org/docs/0.11/api/#application-object)'s instance with `WhiteNoise()`. It doesn't matter if the Flask app created directly (e.g. `app = Flask(__name__)`) or through a _app creator_ (e.g. [something like that](http://flask.pocoo.org/snippets/20/)).

I see no need to package a WhiteNoise Flask extension because integration is so simple (e.g. `app = WhiteNoise(Flask(__name__))`) and the `add_files(…)` (or `root` argument from `WhiteNoise()`) might vary considerably because Flask do not impose any architecture.

However we could mention this in the documentation and maybe offer some example based on the default of having a `static/` directory inside the main app folder.

If this sounds like a goos idea, I can send a PR.

**Comment by evansd** [comment]
@cuducos Thanks very much for this! I'll review that PR as soon as I've got time and merge it in.

**Comment by evansd** [comment]
Closed by 74a0e04980bf23d6d74b667af678026770defdf9
