### ISSUE TITLE
DjangoWhiteNoise doesn't handle multiple slashes in URL the same way as Django

### ISSUE THREAD

**Issue by nottrobin** [evansd/whitenoise#71]
When running with the Django development server, accidental multiple slashes in a URL like `static//global.css` will be converted into `static/global.css`, and so the asset will be served succesfully.

The same URL when served through `DjangoWhiteNoise` will however not find the asset.

This leads to a frustrating situation where the site looks like it works to developers running the site locally but then has errors when pushed to the deployed environment.

Can I suggest that `DjangoWhiteNoise` should tread these URLs the same way Django does?

**Comment by evansd** [comment]
Thanks for reporting this, that is a frustrating situation.

I feel that this a bug with Django's dev server though, rather than behaviour which WhiteNoise should emulate. Longer term there are plans afoot to merge WhiteNoise into Django and use that for serving static files in development, so this difference shouldn't arise.

As an immediate solution, you could use `./manage.py runserver --nostatic` to disable Django's static file handling and let WhiteNoise take over. This will give you better consistency between dev and production, which has benefits beyond just this multiple slashes issue.

**Comment by nottrobin** [comment]
Thanks @evansd, that is a better solution.

Is there any way to declare `--nostatic` in the Django settings file? Or any way whereby I don't have to always pass it as a parameter?

**Comment by evansd** [comment]
Annoyingly there isn't. The only way I can think of to get around this is to create a new `runserver.py` management command in an app which comes above `django.contrib.staticfiles` in the `INSTALLED_APPS` list. The file would just have to contain:
```python
from django.core.management.commands.runserver import Command
```
This would then shadow the `staticfiles` runserver command and replace it with the default one.

Not the simplest solution though.

**Comment by bittner** [comment]
@nottrobin Now there is a way to "declare `--nostatic` in the settings", [see the docs](https://whitenoise.readthedocs.io/en/stable/django.html#using-whitenoise-in-development). They say:

``` python
INSTALLED_APPS = [
    # ...
    'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    # ...
]
```

**Comment by nottrobin** [comment]
@bittner ah wonderful! Thanks for letting me know.
