### ISSUE TITLE
Staats, please

### ISSUE THREAD

**Issue by techtonik** [evansd/whitenoise#78]
Was there any attempts to measure stats and build graphics? That would be very compelling.

Great project, anyways.

**Comment by evansd** [comment]
Can you give an example of the kind of thing you were thinking of?

**Comment by techtonik** [comment]
Something like this:

![](http://www.labs.hpe.com/research/linux/httperf/wisp98/html/img000.gif)

http://www.labs.hpe.com/research/linux/httperf/wisp98/html/doc003.html


Also good graphs are here: http://nichol.as/benchmark-of-python-web-servers

They may be missing the key indicator for static serving - the "throughput" - how many gigabytes are sent per request/CPU/memory.

**Comment by techtonik** [comment]
Also RPS - https://nbonvin.wordpress.com/2011/03/14/apache-vs-nginx-vs-varnish-vs-gwan/

**Comment by techtonik** [comment]
Some kb/sec research for Tomcat - https://tomcat.apache.org/articles/benchmark_summary.pdf

**Comment by techtonik** [comment]
Tools:

 - ab -https://httpd.apache.org/docs/2.4/programs/ab.html - RPS
 - httperf - https://github.com/httperf/httperf - looks like capable of measuring traffic per second too
 
Actually they all are there - https://en.wikipedia.org/wiki/Web_server_benchmarking - but of course a diagram is more convincing than tables.

**Comment by evansd** [comment]
Ah I see. "Benchmarking" is the term I would use here, "stats" makes me think of web usage analytics, but anyway I get what you mean now.

I've tried to explain [here](http://whitenoise.evans.io/en/stable/#isn-t-serving-static-files-from-python-horribly-inefficient) why performance benchmarking doesn't make a lot of sense for this project. No pure-Python solution will ever compete with Apache/nginx at this kind of task. But what WhiteNoise does it to get your caching headers right so you can serve all your static files behind a CDN which will get you better overall performance than running Apache/nginx anyway.

I did a quick experiment once benchmarking WhiteNoise against nginx and got something like 15% of the reqs/second that nginx can do, which seemed pretty good to me. But I decided against writing this up properly because I want to encourage people to just use a CDN wherever performance is a concern.

Hope that makes sense.

**Comment by techtonik** [comment]
So WhiteNoise doesn't use `sendfile` call itself. It that impossible to do from Python?

**Comment by techtonik** [comment]
Benchmark will be nice to have, anyway.

**Comment by evansd** [comment]
WhiteNoise itself can't make the decision to use or not use `sendfile` because it doesn't have direct access to the socket. It calls `wsgi.file_wrapper` and it's up to the WSGI server whether it implements that using `sendfile` or not. Gunicorn does, but not all other WSGI servers do.

Of course nginx uses `sendfile` as well, so when comparing the two you're really comparing how fast they can parse HTTP headers, and nginx easily wins.

I'll add a note to produce some benchmarks when I have the time.

**Comment by techtonik** [comment]
That explains it a bit. Thanks.

**Comment by evansd** [comment]
Realistically, I'm not going to get round to producing benchmarks anytime soon.
