### ISSUE TITLE
Support for WSGI SCRIPT_NAME

### ISSUE THREAD

**Issue by adborden** [evansd/whitenoise#88]
I'm configuring my django app under a prefix using [WSGI's SCRIPT_NAME](https://www.python.org/dev/peps/pep-0333/), but `whitenoise` doesn't seem to pick up on this.

I'm using django configured with [waitress's url_prefix](http://docs.pylonsproject.org/projects/waitress/en/latest/#using-url-prefix-to-influence-script-name-and-path-info)  and django's `STATIC_URL` with the prefix i.e.

```
waitress-serve --url-prefix /prefix
...
STATIC_URL = '/prefix/static/'
```

Whitenoise's django middleware indexes the static files with `/prefix/static/` but then `PATH_INFO` starts with `/static/` and never matches any files.

I've been able to work around this by avoiding the django middleware and instead using:
```
waitress-serve --url-prefix /prefix
...
STATIC_URL = '/prefix/static/'
...
application = WhiteNoise(
    get_wsgi_application(),
    root=settings.STATIC_ROOT,
    prefix='/static/'
)
```

**Comment by evansd** [comment]
Thanks for reporting this. It ought to be possible to get WhiteNoise to "Just Work" under this configuration but I haven't quite figured out the best way to make this happen. I'll do a bit more investigation and issue a new release once I've got an acceptable solution.

**Comment by evansd** [comment]
@adborden I've addded a `WHITENOISE_STATIC_PREFIX` setting which lets you set the static file prefix independently of `STATIC_URL` and should let you accomplish what you want:
http://whitenoise.evans.io/en/stable/django.html#WHITENOISE_STATIC_PREFIX

I tried to avoid adding an extra config setting but it turned out to more complex than I thought to handle this kind of case automatically.

If you're making changes to your WhiteNoise config anyway I'd encourage you to move to the simpler Django middleware integration, rather than the old wsgi.py approach:
http://whitenoise.evans.io/en/latest/changelog.html#simpler-cleaner-django-middleware-integration
