### ISSUE TITLE
slowed tests

### ISSUE THREAD

**Issue by oppianmatt** [evansd/whitenoise#94]
Adding the whitenoise middleware can greatly slow down your tests. If you have processes static previously and your static directory is full of static files. Then the middleware, on each test method, process the list of files over and over. So your tests are now slowed by a function of how many static files you have.

On startup this is called:

```
    def update_files_dictionary(self, root, prefix):
        for directory, _, filenames in os.walk(root, followlinks=True):
            for filename in filenames:
                path = os.path.join(directory, filename)
                url = prefix + os.path.relpath(path, root).replace('\\', '/')
                self.files[url] = self.get_static_file(path, url)
```

And if you have thousands of static files, this will slow it down.

Perhaps this list could be lazy loaded on first call rather than init.

**Comment by evansd** [comment]
I think easiest solution here would be to set `STATIC_ROOT` to point to a new, empty directory when running the tests. This is preferable in any case as you don't want your tests to accidentally depend on whether you've run `collectstatic` previously or not.

**Comment by edmorley** [comment]
It sounds like the tests are being run without Django `DEBUG` being set, otherwise auto-refresh would be enabled, which stops the on-init call to `update_files_dictionary()`.

So as an alternative to setting `STATIC_ROOT` (and also `WHITENOISE_ROOT`, if you use that too) to a test only location, you could try forcing `WHITENOISE_AUTOREFRESH` to `True` during tests:
http://whitenoise.evans.io/en/stable/django.html#WHITENOISE_AUTOREFRESH

**Comment by edmorley** [comment]
Though if you do that, you'll likely also want to set `WHITENOISE_USE_FINDERS` to `True` too, otherwise you'll end up with any requests for the static assets only finding potentially stale assets in the collectstatic target directory.

I agree with David that avoiding accidental dependency on running collectstatic is probably preferable.

**Comment by oppianmatt** [comment]
tests are always run with DEBUG=False as that's what django does:

https://docs.djangoproject.com/en/1.9/topics/testing/overview/#other-test-conditions

> Regardless of the value of the DEBUG setting in your configuration file, all Django tests run with DEBUG=False. This is to ensure that the observed output of your code matches what will be seen in a production setting.

**Comment by oppianmatt** [comment]
My fix in my test specific settings:

```
# remove these middlewares
MIDDLEWARE_CLASSES_REMOVE = [
    # slow if you have lots of static
    'whitenoise.middleware.WhiteNoiseMiddleware',
]
MIDDLEWARE_CLASSES = list(MIDDLEWARE_CLASSES)
for remove_middleware in MIDDLEWARE_CLASSES_REMOVE:
    MIDDLEWARE_CLASSES.remove(remove_middleware)

```

**Comment by joshblum** [comment]
@evansd can this issue be reopened until a fix is in place? This has been slowing down our tests for months and we've invested a lot of engineering time into other optimizations while trying to track down the cause until by accident we realized it was related to whitenoise.

**Comment by evansd** [comment]
I don't think this behaviour is going to be changed in any fundamental way. Later versions of WhiteNoise may use the more efficient filesystem APIs available in Python 3.5 which should make things faster, but it will be still scan all static files on start up. This behaviour is designed for production settings where trading slower startup time for faster response time makes perfect sense.

If your tests don't involve static files then you can either remove the WhiteNoise middleware or just make sure that `STATIC_ROOT` points to an empty directory (as in the comments above).

For tests which _do_ involve static files, your best option is to try to only create a single application instance and run all your static file tests against that so you only pay the start up cost once.

In any case, if you're having performance issues always profile before investing engineering time in optimisations (I recommend playing with [SnakeViz](https://jiffyclub.github.io/snakeviz/) if you haven't already). Discovering your bottlenecks by accident is never fun ;)

**Comment by joshblum** [comment]
@evansd totally agree, just think it should be documented more prominently than a closed issue (unless I missed it in the docs somewhere) so that most people don't end up with inefficient installations. Would you guys be interested in a PR to explain this during the install? I can work on something and submit it.

**Comment by oppianmatt** [comment]
note this doesn't also just make tests slow
we had this kill our production servers a few days ago due to this
we have started to add node_modules into our static directory, and this pulled a LOT of files with it
most of them unused
but these were baked into our docker image like the rest of the static files

what then happened is our deploys were killing the servers
on startup the aforementioned `update_files_dictionary` would run 
which enumerates and checks all files
BUT it does this for each gunicorn worker instead of once for the master
even though it's the same information for each worker, they are all still hitting the filesystem for every file for every gunicorn worker process, all at the same time for a nice herd stampede

so this issue really isn't fixed, and more importantly this issue does affect production and slows down (or even kills) a deploy

note we are using manifest static storage so it shouldn't even need to walk the filestem, it could load up the staticfiles.json to know what files are there

or if you do need to walk the filesystem, do you really need to do it X times (where X is the number of gunicorn workers)? Perhaps you could use caching to reduce the fs load.

**Comment by oppianmatt** [comment]
perhaps a simple fix for now could be to replace `os.walk` with `scandir`
yes scandir is only for 3.5 but can use a replacement for 2.7 like https://pypi.python.org/pypi/scandir

> In practice, removing all those extra system calls makes os.walk() about 7-50 times as fast on Windows, and about 3-10 times as fast on Linux and Mac OS X. So we’re not talking about micro-optimizations

**Comment by edmorley** [comment]
Also perhaps mentioning in the documentation that it's recommended to disabling file scanning during tests?

**Comment by oppianmatt** [comment]
yeah we ended up moving our node_modules directory (really was a jspm_packages as experimenting with jspm/systemjs, but everyone knows what node_modules is and the pain it causes) in the end.

And building bundles using django's static mangament tools are a pain

And with http2 the argument for creating bundles is reduced since the requests are all multiplexed in one request, no slow start tcp connections. You do have to watch for deep depends so bundling still can ahve a place (although we now have deep depends detection )

**Comment by evansd** [comment]
Yes, including node_modules inside the static directory isn't going to end well so I'd avoid that if at all possible. The setup I generally have is:
```
./static_src (which possibly includes node_modules)
        ↓
  [frontend build tool de jour]
        ↓
./static_build
        ↓
  [ manage.py collectstatic ]
        ↓
./static_root
```
So Django doesn't need to know anything about the build tool I'm using or how the original source files are laid out, it just picks up the build artifacts from `static_build`.

There are definitely some optimisations that can be made (using `scandir` and some other tricks) to reduce the amount of disk IO during start up and I'll look into doing that before too long.

@oppianmatt The static manifest isn't sufficient by itself, because we need to know the sizes of all the files and also whether the corresponding compressed versions exist.

It ought to be possible to cache the entirety of WhiteNoise's state by pickling the `self.files` attribute to a file somewhere, but then that's an extra layer of complexity to manage which probably won't be worthwhile for most users.

The file scan is happening for each worker because gunicorn is configured to boot multiple versions of the app, each in its own process. You can use the [preload](http://docs.gunicorn.org/en/stable/settings.html#server-mechanics) option to boot a single copy of the app and then fork it into multiple workers.

**Comment by joshblum** [comment]
@evansd the static layout is helpful we were considering moving to something similar. I think all of this should be introduced into the documentation so it is easier to get setup and not have issues as you add more static assets and the problems become more prominent. Would you be open to a PR to address this?

**Comment by evansd** [comment]
@joshblum Yes, I think it would be a good idea to add guidance on this to the docs -- I should have done this earlier, really. Contributions are definitely welcome but I should warn you then I get a bit fussy about documentation so don't be offended if I end up rewriting lots of it!

**Comment by evansd** [comment]
The file scanning code has now been rewritten to be as IO efficient as I can make it (including using scandir where this is available). I've also added a section on slow tests in the docs with suggestions for workarounds.

**Comment by joshblum** [comment]
Awesome 😎:)

**Comment by cjerdonek** [comment]
I'm new to whitenoise and just saw this issue after running into it.

@evansd's idea to store the result of walking the directory in a file occurred to me, too, and I think makes a lot of sense:

> It ought to be possible to cache the entirety of WhiteNoise's state by pickling the self.files attribute to a file somewhere, 

It seems like this would be an especially good fit e.g. for people using Docker. The file could be generated as part of the Docker build and stored in the Docker image itself.

I'm not sure if there's already an open issue for this feature, but it does relate to the general issue #141 ("Make whitenoise faster"), which is still open.
