### ISSUE TITLE
[Django] Third-party library missing a file triggers a `MissingFileError`

### ISSUE THREAD

**Issue by fabionatali** [evansd/whitenoise#96]
# Intro

My Django project relies on a few third-party JS/CSS libraries that get installed via Bower.

One of those libraries refers to a static file that happens not to be included in the library itself. This triggers a `MissingFileError` when `collectstatic` is run.

# Details

While the missing file is clearly a bug in the JS/CSS library I was wondering if there can be a way this can be addressed on the WhiteNoise side. It is also important to note that the missing image is actually an image in the *documentation* of the library, and is not part of the actual JS/CSS core.

```
File "<my-venv>/local/lib/python2.7/site-packages/django/contrib/staticfiles/management/commands/collectstatic.py", line 128, in collect
    raise processed
whitenoise.storage.MissingFileError: The file 'js/lib/bower_components/vis/docs/css/img/search.png' could not be found with <whitenoise.storage.CompressedManifestStaticFilesStorage object at 0x7f86ea101350>.

The CSS file 'js/lib/bower_components/vis/docs/css/tipuesearch.css' references a file which could not be found:
  js/lib/bower_components/vis/docs/css/img/search.png

Please check the URL references in this CSS file, particularly any
relative paths which might be pointing to the wrong location.
```

NB: Compression is enabled in my setup, with `STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'`.

Anyone has any idea on how I should address this? Am I doing something wrong? Is there something in my setup that is not ideal and can be fixed? Or should a way of whitelisting these kind of errors be introduced in some way?

Thanks! ^F

**Comment by evansd** [comment]
Hi @fabionatali,

Thanks for the detailed report. This is an annoying feature (or bug, depending on your point of view) in Django's storage backend which WhiteNoise uses, so it's not something that can be directly fixed in WhiteNoise.

One approach would be to create a subclass of `CompressedManifestStaticFilesStorage` which suppresses the error. It would look something like this:
```python
from whitenoise.storage import CompressedManifestStaticFilesStorage

class ErrorSquashingStorage(CompressedManifestStaticFilesStorage):

    def url(self, name, **kwargs):
        try:
            return super(ErrorSquashingStorage, self).url(name, **kwargs)
        except ValueError:
            return name
````
That's a bit of a hacky solution though.

Another approach would be avoid including the problematic files in your static files. (As they're documentation you probably don't want them as part of your production assets anyway.) What I've done in the past is, rather than having the entire `bower_components` directory included in my main static directory, I've stored it outside that directory and then just symlinked in the specific parts I want. It's a little bit more effort, but it means you have much more control over what ends up in your production assets.

Let me know if any of that helps.

**Comment by fabionatali** [comment]
Hey @evansd,

That definitely helps, thanks for your speedy answer.

Yeah, I agree, it's probably better if I fix the root cause of the problem and get more control on what goes in my static file folder.

I'd consider this closed, I'll raise a new issue in the future if I have further doubts/questions.

Tx, F.
