### ISSUE TITLE
Any URIs with unicode characters in them throw an exception in middleware

### ISSUE THREAD

**Issue by Foslock** [evansd/whitenoise#99]
Whenever a URI is processed through the **whitenoise** middleware, if there are any unicode characters in that URI, an exception is thrown and results in a 500 error if being run in a Django server. This **only occurs when the *autorefresh* setting is *True***. It seemingly only affects development environments.

For example:

```bash
$ curl -X GET http://127.0.0.1:8000/static/
```

will result in a stack trace like so, which is an uncaught exception in Django middleware, causing a 500.

```python
Traceback (most recent call last):
  File ".../lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File ".../lib/python2.7/site-packages/whitenoise/base.py", line 57, in __call__
    static_file = self.find_file(environ['PATH_INFO'])
  File ".../lib/python2.7/site-packages/whitenoise/django.py", line 75, in find_file
    if self.use_finders and url.startswith(self.static_prefix):
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 78: ordinal not in range(128)
```

This can be reproduced on a bare Django project (I am using v1.9.6, Python 2.7.11) simply by configuring the STATIC_URL and adding the whitenoise middleware.

Looking in the library, it seems like when the **PATH_INFO** environment variable is pulled (whitenoise/base.py:57), it is left as a plain byte string instead of being decoded into a unicode object. Decoding this str object at this spot seems to fix my issue, but I don't know if other places need this as well.

It seems the crux of this error can be reproduced by the following code:
```python
>>> b""
'\xef\xa3\xbf'
>>> b"".startswith(u"some text")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 0: ordinal not in range(128)
```

**Comment by evansd** [comment]
Thanks for the detailed bug report. Correctly handling encodings at the WSGI boundary in both Python 2 and 3 is a real minefield!

I'll fix this bug properly when I get the time, but as a quick workaround you could try using the [newer Django middleware](http://whitenoise.evans.io/en/stable/changelog.html#simpler-cleaner-django-middleware-integration) integration instead of the WSGI middleware, which should handle this case correctly.

**Comment by evansd** [comment]
It turns out these URL are [invalid](http://stackoverflow.com/questions/2504564/can-http-uris-have-non-ascii-characters), all non-ascii characters should be percent-encoded. So you might have problems elsewhere if you try to use such URLs in your application.

However, it would be better for WhiteNoise to be able to ignore these URLs rather than blowing up, so I'll still try to fix this bug if possible.
